name: Pipeline 

on:
  push:
    branches:
      - main

jobs:
  analyze-code:
    runs-on: windows-latest
    name: Analyze Code
    uses: yomins/workflow-templates/.github/workflows/analyse.yml@main
    with:
      languages: "['javascript', 'chsarp']"
